var heroes = {
    0: 'Abaddon',
    1: 'Alchemist',
    2: 'Ancient Apparition',
    3: 'Anti-Mage',
    4: 'Arc Warden',
    5: 'Axe',
    6: 'Bane',
    7: 'Batrider',
    8: 'Beastmaster',
    9: 'Bloodseeker',
   10: 'Bounty Hunter',
   11: 'Brewmaster',
   12: 'Bristleback',
   13: 'Broodmother',
   14: 'Centaur Warrunner',
   15: 'Chaos Knight',
   16: 'Chen',
   17: 'Clinkz',
   18: 'Clockwerk',
   19: 'Crystal Maiden',
   20: 'Dark Seer',
   21: 'Dark Willow',
   22: 'Dawnbreaker',
   23: 'Dazzle',
   24: 'Death Prophet',
   25: 'Disruptor',
   26: 'Doom',
   27: 'Dragong Knight',
   28: 'Drow Ranger',
   29: 'Earth Spirit',
   30: 'Earth Shaker',
   31: 'Elder Titan',
   32: 'Ember Spirit',
   33: 'Enchantress',
   34: 'Enigma',
   35: 'Faceless Void',
   36: 'Grimstroke',
   37: 'Gyrocopter',
   38: 'Hoodwink',
   39: 'Huskar',
   40: 'Invoker',
   41: 'Io',
   42: 'Jakiro',
   43: 'Juggernaut',
   44: 'Keeper of the Light',
   45: 'Kunkka',
   46: 'Legion Commander',
   47: 'Leshrac',
   48: 'Lich',
   49: 'Lifestealer',
   50: 'Lina',
   51: 'Lion',
   52: 'Lone Druid',
   53: 'Luna',
   54: 'Lycan',
   55: 'Magnus',
   56: 'Mars',
   57: 'Medusa',
   58: 'Meepo',
   59: 'Mirana',
   60: 'Monkey King',
   61: 'Morphling',
   62: 'Naga Siren',
   63: 'Nature\'s Prophet',
   64: 'Necrophos',
   65: 'Night Stalker',
   66: 'Nyx Assassin',
   67: 'Ogre Magi',
   68: 'Omniknight',
   69: 'Oracle',
   70: 'Outworld Destroyer',
   71: 'Pangolier',
   72: 'Phantom Assassin',
   73: 'Phantom Lancer',
   74: 'Phoenix',
   75: 'Puck',
   76: 'Pudge',
   77: 'Pugna',
   78: 'Queen of Pain',
   79: 'Razor',
   80: 'Riki',
   81: 'Rubick',
   82: 'Sand King',
   83: 'Shadow Demon',
   84: 'Shadow Fiend',
   85: 'Shadow Shaman',
   86: 'Silencer',
   87: 'Skywrath Mage',
   88: 'Slardar',
   89: 'Slark',
   90: 'Snapfire',
   91: 'Sniper',
   92: 'Spectre',
   93: 'Spirit Breaker',
   94: 'Storm Spirit',
   95: 'Sven',
   96: 'Techies',
   97: 'Templar Assassin',
   98: 'Terrorblade',
   99: 'Tidehunter',
  100: 'Timbersaw',
  101: 'Tinker',
  102: 'Tiny',
  103: 'Treant Protector',
  104: 'Troll Warlord',
  105: 'Tusk',
  106: 'Underlord',
  107: 'Undying',
  108: 'Ursa',
  109: 'Vengeful Spirit',
  110: 'Venomancer',
  111: 'Viper',
  112: 'Visage',
  113: 'Void Spirit',
  114: 'Warlock',
  115: 'Weaver',
  116: 'Windranger',
  117: 'Winter Wyvern',
  118: 'Witch Doctor',
  119: 'Wraith King',
  120: 'Zeus',
  121: 'Marci',
};

var tags = [
  'ability draft',
  'aegis steal',
  'bait',
  'base defense',
  'buyback',
  'dodge',
  'farming',
  'final push',
  'first blood',
  'gank',
  'high damage',
  'high ground',
  'juking',
  'kiting',
  'low hp',
  'mid lane',
  'misplay',
  'memeing',
  'outplay',
  'raid boss',
  'rampage',
  'rage quit',
  'roshan fight',
  'save',
  'skill shot',
  'solo kill',
  'team fight',
  'tilted',
  'ultra kill',
];

module.exports.heroes = heroes;
module.exports.tags = tags;
